---
title: "Workout Report 1"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
---

```{r setup, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, fig.width=6.5, fig.height=6.5}
options(stringsAsFactors=FALSE)
knitr::opts_chunk$set(echo=FALSE, fig.height=9, fig.width=6.5, include=TRUE, warning=FALSE, error=FALSE, message=FALSE)
#devtools::install_github("tidyverse/dplyr")
#devtools::install_github("tidyverse/dbplyr")
#devtools::install_github("rstats-db/odbc")
library(foreach)
library(lubridate)
library(tidyverse)
library(knitr)
library(treemapify)
library(magick)
library(grid)

#this sets the darkness of the base muscle group image
transparency_base<-.4
#this sets the range available for color scale of muscle groups...lower is higher range
transparency_reserved<-.1

#prep for images
i<-list()
i$Neck<-image_read("dia/Neck.png")
i$Shoulders<-image_read("dia/Shoulders.png")
i$Back<-image_read("dia/Back.png")
i$Chest<-image_read("dia/Chest.png")
i$Triceps<-image_read("dia/Triceps.png")
i$Biceps<-image_read("dia/Biceps.png")
i$Forearms<-image_read("dia/Forearms.png")
i$Core<-image_read("dia/Core.png")
i$UpperLegs<-image_read("dia/UpperLegs.png")
i$LowerLegs<-image_read("dia/LowerLegs.png")
i$Glutes<-image_read("dia/Glutes.png")
i$WholeBody<-image_read("dia/WholeBody.png")
i$Base<-image_read("dia/Base_Gray.png")


createDiaLayer<-function(img, transparency=0.8){
  bitmap<-img[[1]]
  bitmap[4,,]<-as.raw(as.integer(bitmap[4,,])*transparency)
  img<-image_read(bitmap)
  return(img)
}

```


```{r getData}
e_s<-read.csv(file="data/exercises_strength.csv") 

d_s<-read.csv(file="data/strength.csv") %>% mutate(date1=mdy(Date)) %>% filter(date1>mdy("2/23/2020"))
```


```{r wrangleData}
#ensure all exercises are present in the coding file

#use "edit_exercises.R" script now

# e_s<-d_s %>%
#   select(Exercise) %>%
#   unique()
# e_s$Group1<-c("Chest","Core","Chest","Shoulders","Biceps","Shoulders","Biceps","Core","Chest","Back","Triceps","Chest","Core","Core","Core","Back","Core","Core","Core","Back","Core","Core","Shoulders","Core","Biceps","Triceps","Chest","Biceps","Back","Chest","Shoulders","LowerLegs","Shoulders","Shoulders","Core","Compound","Triceps","Core","Biceps","Chest","Biceps","Triceps","Shoulders","Core","Shoulders","UpperLeg","Core","Compound","Compound","WholeBody","WholeBody",'WholeBody',"UpperLeg","Core","Core","Chest","Core","Biceps","Core")
# 
# write.csv(e_s, file="data/exercises_strength.csv")


```


```{r createDataset}
d_s<-d_s %>%
  rename(Reps=X..of.Reps) %>%
  left_join(e_s, by=c("Exercise")) %>% 
  mutate(Group1=ifelse(is.na(Group1), "Unspecified", Group1))

```


```{r}
tmp<-d_s %>%
  group_by(Exercise) %>%
  select(Group1) %>%
  unique()

kable(tmp)
```

\newpage

\newpage
## Volumes

```{r TotalWeightsByExercise}
tmp<-d_s %>%
  filter(Weight>0) %>%
  group_by(Group1, Exercise) %>%
  summarise(volume_Exercise=sum(Weight * Reps)) %>%
  group_by(Group1) %>%
  mutate(volume_Group1=sum(volume_Exercise)) %>%
  ungroup() %>%
  mutate(volume_Total=sum(volume_Exercise)) %>%
  mutate(percent_of_Group1=round(volume_Exercise/volume_Group1 * 100,1),
         percent_of_Total=round(volume_Exercise/volume_Total * 100,1)) %>%
  select(-volume_Group1, -volume_Total)
```



```{r fig.height=5}
# plot
ggplot(tmp,aes(area=volume_Exercise, fill=Group1, subgroup=Group1)) +
  geom_treemap() +
  geom_treemap_text(aes(label=Exercise),place = "topleft", grow = FALSE, size=6, reflow=FALSE) +
  geom_treemap_subgroup_text(place = "centre", grow = TRUE, alpha = 0.25, angle=45) + 
  theme(legend.position = "none") +
  labs(title="Volume")

```

```{r}
kable(tmp)
```

```{r TotalWeightsByGroup}
tmp<-d_s %>%
  filter(Weight>0) %>%
  group_by(Group1) %>%
  summarise(volume_Group1=sum(Weight*Reps)) %>%
  ungroup() %>%
  mutate(volume_Total=sum(volume_Group1)) %>%
  mutate(percent_of_Total=round(volume_Group1/volume_Total * 100,1)) %>%
  select(-volume_Total)

kable(tmp)
```

```{r }

tmp_img<-foreach(x=tmp$Group1, .combine="list") %do% {
  if(x %in% c("Neck", "Shoulders", "Back", "Chest", "Core", "UpperLegs", "LowerLegs", "Biceps", "Triceps", "Forearms", "WholeBody")){
        createDiaLayer(img=i[[as.character(x)]], transparency=as.numeric(tmp[tmp$Group1==x, c("percent_of_Total")])/(100-(transparency_reserved*100))+transparency_reserved)
    }
}

tmp_img2<-image_flatten(c(createDiaLayer(i[["Base"]], transparency_base),tmp_img)) %>%
  image_resize("700")

grid.raster(tmp_img2)
```


\newpage



## Reps

```{r TotalRepsByExercise}
tmp<-d_s %>%
  group_by(Group1, Exercise) %>%
  summarise(reps_Exercise=sum(Reps)) %>%
  group_by(Group1) %>%
  mutate(reps_Group1=sum(reps_Exercise)) %>%
  ungroup() %>%
  mutate(reps_Total=sum(reps_Exercise)) %>%
  mutate(percent_of_Group1=round(reps_Exercise/reps_Group1 * 100,1),
         percent_of_Total=round(reps_Exercise/reps_Total * 100,1)) %>%
  select(-reps_Group1, -reps_Total)
```


```{r fig.height=5}
# plot
ggplot(tmp,aes(area=reps_Exercise, fill=Group1, subgroup=Group1)) +
  geom_treemap() +
  geom_treemap_text(aes(label=Exercise),place = "topleft", grow = FALSE, size=6, reflow=TRUE) +
  geom_treemap_subgroup_text(place = "centre", grow = TRUE, alpha = 0.25, angle=45) + 
  theme(legend.position = "none")


```


```{r}
kable(tmp)
```


```{r TotalRepsByGroup}
tmp<-d_s %>%
  group_by(Group1) %>%
  summarise(reps_Group1=sum(Reps)) %>%
  ungroup() %>%
  mutate(reps_Total=sum(reps_Group1)) %>%
  mutate(percent_of_Total=round(reps_Group1/reps_Total * 100,1)) %>%
  select(-reps_Total)

kable(tmp)
```

```{r}
tmp_img<-foreach(x=tmp$Group1, .combine="list") %do% {
  if(x %in% c("Neck", "Shoulders", "Back", "Chest", "Core", "UpperLegs", "LowerLegs", "Biceps", "Triceps", "Forearms", "WholeBody")){
        createDiaLayer(img=i[[as.character(x)]], transparency=as.numeric(tmp[tmp$Group1==x, c("percent_of_Total")])/(100-(transparency_reserved*100))+transparency_reserved)
    }
}

tmp_img2<-image_flatten(c(createDiaLayer(i[["Base"]], transparency_base),tmp_img)) %>%
  image_resize("700")

grid.raster(tmp_img2)
```


\newpage
## Exercises Through Time

```{r AveWeightsByExercise}
tmp<-d_s %>%
  mutate(Volume=(Reps*Weight),
         OneRM=Weight*(1+(Reps/30)),
         Sets=1) %>%
  select(Date, Exercise, Reps, Sets, Weight, Volume, OneRM) %>%
  group_by(Exercise) %>%
  mutate(numDays=n_distinct(Date)) %>%
  filter(numDays>3) %>%
  select(-numDays) %>%
  group_by(Date, Exercise) %>%
  summarise(numDays=n_distinct(Date), 
            aveWeight=mean(Weight), maxWeight=max(Weight),
            aveReps=mean(Reps), maxReps=max(Reps),
            numSets=sum(Sets),
            totVolume=sum(Volume),
            maxOneRM=max(OneRM)) %>%
  gather(Measure, Value, -c(1:3)) %>%
  separate(Measure, c("Measure", "Variable"),sep=3) %>%
  mutate(Measure=factor(Measure, levels=c("ave", "max", "num", "tot"), labels=c("Average", "Max", "Number", "Total"))) %>%
  mutate(Variable=factor(Variable, levels=c("Volume", "Weight", "Reps", "Sets", "OneRM", "Days"))) %>%
  ungroup() %>%
  mutate(Date=mdy(Date))


for(myExercise in unique(tmp$Exercise)) {
 
t<-ggplot(tmp %>% filter(Exercise==myExercise)) +
  geom_line(aes(x=Date, y=Value, group=Measure, linetype=Measure, color=Measure), size=2) +
  geom_point(aes(x=Date, y=Value, group=Measure, color=Measure), size=3.5) +
  labs(title=myExercise, y="", x="") +
  facet_wrap(~Variable, ncol=1, scales="free_y") +
    theme_bw()

print(t)
}
```

## Group Through Time

```{r AveWeightsByGroup}
tmp<-d_s %>%
  mutate(Volume=(Reps*Weight),
         Sets=1) %>%
  select(Date, Group1, Reps, Sets, Weight, Volume) %>%
  group_by(Group1) %>%
  mutate(numDays=n_distinct(Date)) %>%
  filter(numDays>3) %>%
  select(-numDays) %>%
  group_by(Date, Group1) %>%
  summarise(numDays=n_distinct(Date), 
            aveWeight=mean(Weight), maxWeight=max(Weight),
            aveReps=mean(Reps), maxReps=max(Reps),
            numSets=sum(Sets),
            totVolume=sum(Volume)) %>%
  gather(Measure, Value, -c(1:2)) %>%
  separate(Measure, c("Measure", "Variable"),sep=3) %>%
  mutate(Measure=factor(Measure, levels=c("ave", "max", "num", "tot"), labels=c("Average", "Max", "Number", "Total"))) %>%
  mutate(Variable=factor(Variable, levels=c("Volume", "Weight", "Reps", "Sets")))
  
for(myGroup1 in unique(tmp$Group1)) {
 
t<-ggplot(tmp %>% filter(Group1==myGroup1)) +
  geom_line(aes(x=Date, y=Value, group=Measure, linetype=Measure, color=Measure), size=2) +
    labs(title=myGroup1, y="", x="") +
  facet_wrap(~Variable, ncol=1, scales="free_y") +
    theme_bw()

print(t)
}
```